// Builds the WebAssembly core into `src/wasm/` for the npm package.
//
// The `.wasm` binary is embedded as base64 so the package works the same in
// Node.js, browsers and the UMD build, with a synchronous `format()` and no
// asset loading for consumers to configure.

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const outDir = `${root}src/wasm`;

execFileSync(
  'wasm-pack',
  [
    'build',
    'crates/annealer',
    '--target',
    'web',
    '--out-dir',
    outDir,
    '--out-name',
    'annealer',
    '--profile',
    'wasm-release',
    '--no-pack',
    '--',
    '--no-default-features',
    '--features',
    'wasm'
  ],
  { cwd: root, stdio: 'inherit' }
);

// The glue's default loader resolves the binary with `new URL(…, import.meta.url)`,
// which bundlers turn into an emitted asset (and UMD can't express). The
// wrapper always passes the embedded bytes, so the fallback is removed.
const gluePath = `${outDir}/annealer.js`;
const fallback = "new URL('annealer_bg.wasm', import.meta.url)";
const glue = readFileSync(gluePath, 'utf8');
if (!glue.includes(fallback)) {
  throw new Error(
    `${gluePath}: wasm-bindgen output changed; update scripts/build-wasm.mjs`
  );
}
writeFileSync(
  gluePath,
  glue.replace(
    fallback,
    "(() => { throw new Error('annealer: the WebAssembly binary is embedded; use initSync'); })()"
  )
);

const wasm = readFileSync(`${outDir}/annealer_bg.wasm`);
writeFileSync(
  `${outDir}/binary.ts`,
  `// Generated by scripts/build-wasm.mjs. Do not edit.\nexport const wasmBase64: string =\n  '${wasm.toString('base64')}';\n`
);
